#! /bin/sh

sxhkd &
$HOME/.config/polybar/launch.sh

bspc monitor -d I II III IV

bspc config border_width         4
bspc config window_gap          32

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config top_padding 55
bspc config left_padding 50
bspc config right_padding 50
bspc config bottom_padding 50

feh --bg-center $(find ~/Bilder/Wallpaper -type f | shuf -n 1)